# Generated by Django 5.2.7 on 2025-11-14 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=300)),
                ('full_desc', models.TextField()),
                ('wallpaper', models.ImageField(upload_to='wallpapers/')),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('link_to_instagram', models.URLField()),
                ('link_to_vk', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
