# Generated by Django 5.2.7 on 2025-12-03 14:07

import apps.profiles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, default='', max_length=20)),
                ('last_name', models.CharField(blank=True, default='', max_length=20)),
                ('profession', models.CharField(blank=True, default='', max_length=50)),
                ('short_desc', models.CharField(blank=True, default='', max_length=300)),
                ('full_desc', models.TextField(blank=True, default='')),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.user_wallpaper_path)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.user_avatar_path)),
                ('link_to_instagram', models.URLField(blank=True, default='')),
                ('link_to_telegram', models.URLField(blank=True, default='')),
                ('link_to_github', models.URLField(blank=True, default='')),
                ('link_to_vk', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
