# Generated by Django 5.2.7 on 2025-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_level',
            field=models.CharField(choices=[('not', 'не указано'), ('first_middle', '11 классов'), ('primary_voc_edu', 'Начальное профессиональное образование'), ('secondary_voc_edu', 'Среднее профессиональное образование'), ('higher_voc_edu', 'Высшее профессиональное образование')], default='not', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='relocation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_format',
            field=models.CharField(choices=[('office', 'офис'), ('hybrid', 'гибрид'), ('remote', 'удаленно'), ('any', 'любой')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Senior Product Manager | Growth & Monetization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
