# Generated by Django 5.2.7 on 2025-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_city_profile_country_profile_edu_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianEduLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_middle', models.BooleanField(blank=True, default=False)),
                ('primary_voc_edu', models.BooleanField(blank=True, default=False)),
                ('secondary_voc_edu', models.BooleanField(blank=True, default=False)),
                ('higher_voc_edu', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Уровни государственного образования',
                'verbose_name_plural': 'Уровни государственного образования',
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.BooleanField(blank=True, default=False)),
                ('hybrid', models.BooleanField(blank=True, default=False)),
                ('remote', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Форматы работы',
                'verbose_name_plural': 'Форматы работы',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_levels',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.russianedulevels'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_formats',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.workformat'),
        ),
    ]
