# Generated by Django 5.2.7 on 2025-12-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_russianedulevels_workformat_profile_edu_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='edu_levels',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_formats',
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_levels',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.russianedulevels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='work_formats',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.workformat'),
            preserve_default=False,
        ),
    ]
