# Generated by Django 5.2.7 on 2025-12-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_edu_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='edu_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_format',
        ),
    ]
