# Generated by Django 5.2.7 on 2025-12-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_edu_level_remove_profile_work_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='edu_levels',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_formats',
        ),
        migrations.AddField(
            model_name='workformat',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_formats', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RussianEduLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_middle', models.BooleanField(blank=True, default=False)),
                ('primary_voc_edu', models.BooleanField(blank=True, default=False)),
                ('secondary_voc_edu', models.BooleanField(blank=True, default=False)),
                ('higher_voc_edu', models.BooleanField(blank=True, default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edu_level', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Уровни государственного образования',
                'verbose_name_plural': 'Уровни государственного образования',
            },
        ),
        migrations.DeleteModel(
            name='RussianEduLevels',
        ),
    ]
