# Generated by Django 5.2.7 on 2025-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_edu_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='russianedulevel',
            name='nothing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
