# Generated by Django 5.2.7 on 2025-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_russianedulevel_nothing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='russianedulevel',
            name='first_middle',
        ),
        migrations.RemoveField(
            model_name='russianedulevel',
            name='higher_voc_edu',
        ),
        migrations.RemoveField(
            model_name='russianedulevel',
            name='nothing',
        ),
        migrations.RemoveField(
            model_name='russianedulevel',
            name='primary_voc_edu',
        ),
        migrations.RemoveField(
            model_name='russianedulevel',
            name='secondary_voc_edu',
        ),
        migrations.AddField(
            model_name='russianedulevel',
            name='edu_level',
            field=models.CharField(blank=True, choices=[('nothing', 'не указано'), ('first_middle', '11 классов'), ('primary_voc_edu', 'Начальное профессиональное образование'), ('secondary_voc_edu', 'Среднее профессиональное образование'), ('higher_voc_edu', 'Высшее профессиональное образование')], default='nothing', max_length=30),
        ),
    ]
