# Generated by Django 5.2.7 on 2025-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_russianedulevel_first_middle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edu_level',
            field=models.CharField(blank=True, choices=[('nothing', 'не указано'), ('first_middle', '11 классов'), ('primary_voc_edu', 'Начальное профессиональное образование'), ('secondary_voc_edu', 'Среднее профессиональное образование'), ('higher_voc_edu', 'Высшее профессиональное образование')], default='nothing', max_length=30),
        ),
        migrations.DeleteModel(
            name='RussianEduLevel',
        ),
    ]
