# Generated by Django 5.2.7 on 2025-12-15 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_edu_level_delete_russianedulevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_level',
            field=models.CharField(blank=True, choices=[('nothing', 'не указано'), ('school_9', '9 классов'), ('school_11', '11 классов'), ('ptu', 'ПТУ / Профессиональное училище'), ('technical_school', 'Техникум'), ('college', 'Колледж'), ('unfinished_higher', 'Неоконченное высшее'), ('bachelor', 'Бакалавр'), ('specialist', 'Специалист'), ('master', 'Магистр'), ('phd', 'Кандидат наук'), ('doctor', 'Доктор наук'), ('mba', 'MBA')], default='nothing', max_length=30),
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень владения')),
                ('is_current', models.BooleanField(default=True, verbose_name='Используется ли сейчас')),
                ('privacy', models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости конкретного навыка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='profiles.profile', verbose_name='Профиль')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='profiles.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователя',
                'ordering': ['-level', 'skill'],
                'indexes': [models.Index(fields=['profile', 'level'], name='profiles_pr_profile_cf3149_idx'), models.Index(fields=['profile', 'is_current'], name='profiles_pr_profile_607eb8_idx')],
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
