# Generated by Django 5.2.7 on 2025-12-16 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_skill_alter_profile_edu_level_profileskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень владения'),
        ),
    ]
