# Generated by Django 5.2.7 on 2026-01-08 11:38

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Название темы/раздела знаний')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='MyKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('privacy', models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='nobody')),
                ('topic', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название темы/раздела знаний')),
                ('note', models.TextField(null=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='my_knowledge.myknowledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мои знания',
                'verbose_name_plural': 'Мои знания',
                'indexes': [models.Index(fields=['privacy'], name='my_knowledg_privacy_871b55_idx'), models.Index(fields=['user', 'privacy'], name='my_knowledg_user_id_30f9a1_idx'), models.Index(fields=['tree_id', 'lft'], name='my_knowledge_myknowledge_t866f')],
            },
        ),
    ]
