# Generated by Django 5.2.7 on 2026-01-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_note', serialize=False, to='my_knowledge.myknowledge')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='myknowledge',
            name='note',
        ),
    ]
