# Generated by Django 5.2.7 on 2026-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myknowledge',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='myknowledge',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
