# Generated by Django 5.2.7 on 2026-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_knowledge', '0002_myknowledge_is_deleted_myknowledge_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myknowledge',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
