# Generated by Django 5.2.7 on 2025-12-17 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cart_items', models.JSONField(blank=True, default=list)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('migrated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='guest_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_user', to='accounts.guestuser'),
        ),
        migrations.AddIndex(
            model_name='guestuser',
            index=models.Index(fields=['guest_id'], name='accounts_gu_guest_i_a291cb_idx'),
        ),
        migrations.AddIndex(
            model_name='guestuser',
            index=models.Index(fields=['created_at'], name='accounts_gu_created_e0bc6b_idx'),
        ),
    ]
