# Generated by Django 5.2.7 on 2025-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='unique_any_email_per_user'),
        ),
    ]
