# Generated by Django 5.2.7 on 2025-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_unique_any_email_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='email',
            name='unique_active_email_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='email',
            name='unique_confirmed_email',
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_confirmed', True)), fields=('user', 'is_active', 'is_confirmed'), name='unique_active_email_per_user'),
        ),
    ]
