# Generated by Django 5.2.7 on 2025-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_comfirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
