# Generated by Django 5.2.7 on 2025-12-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guestuser_user_guest_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(max_length=50)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('consent_text_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guestuser')),
            ],
        ),
    ]
