# Generated by Django 5.2.7 on 2025-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_guestconsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestuser',
            options={'verbose_name': 'Гостевой пользователь', 'verbose_name_plural': 'Гостевые пользователи'},
        ),
        migrations.RemoveIndex(
            model_name='guestuser',
            name='accounts_gu_guest_i_a291cb_idx',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='session_key',
        ),
        migrations.AddIndex(
            model_name='guestuser',
            index=models.Index(fields=['ip_address'], name='accounts_gu_ip_addr_40dc66_idx'),
        ),
    ]
