# Generated by Django 5.2.7 on 2025-12-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_guestuser_guest_uuid_user_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='guest_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
