# Generated by Django 5.2.7 on 2025-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='yandex_cookie_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
