# Generated by Django 5.2.7 on 2025-12-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_guestuser_yandex_cookie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='yandex_cookie_id',
        ),
    ]
