# Generated by Django 5.2.7 on 2025-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_confirmation_code_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_code_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
