# Generated by Django 5.2.7 on 2025-12-22 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('backlog', 'Бэклог'), ('ready', 'Готово к работе'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнено'), ('cancelled', 'Отменено')], default='backlog', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Критичный')], default=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_ready', models.DateTimeField(blank=True, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('estimated_effort', models.PositiveIntegerField(blank=True, help_text='Оценка трудозатрат в часах', null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='CycleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('lead_time', 'Полное время (от создания до завершения)'), ('process_time', 'Чистое время работы (от старта до завершения)'), ('waiting_time', 'Время ожидания (создание -> старт)'), ('review_time', 'Время проверки')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField(editable=False)),
                ('notes', models.TextField(blank=True, help_text='Что происходило на этом этапе? Блокировки, причины задержек')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to='my_workflows.task')),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
    ]
