# Generated by Django 5.2.7 on 2025-12-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='privacy',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='nobody', max_length=10),
        ),
    ]
