# Generated by Django 5.2.7 on 2025-12-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0002_task_privacy'),
        ('profiles', '0011_alter_profileskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='profiles.profile'),
        ),
    ]
