# Generated by Django 5.2.7 on 2025-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0003_task_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycletime',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Бэклог'), ('ready', 'Готово к работе'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнено'), ('cancelled', 'Отменено'), ('deleted', 'Удалено')], default='backlog', max_length=20),
        ),
    ]
