# Generated by Django 5.2.7 on 2025-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0004_alter_cycletime_end_time_alter_cycletime_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletime',
            name='duration_hours',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cycletime',
            name='notes',
            field=models.TextField(blank=True, help_text='Что происходило на этом этапе? Блокировки, причины задержек', null=True),
        ),
    ]
