# Generated by Django 5.2.7 on 2025-12-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0005_alter_cycletime_duration_hours_alter_cycletime_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletime',
            name='phase',
            field=models.CharField(choices=[('lead_time', 'Полное время (от создания до завершения)'), ('process_time', 'Чистое время работы (от старта до завершения)'), ('waiting_time', 'Время ожидания (создание -> старт)'), ('review_time', 'Время проверки')], default='lead_time', max_length=20),
        ),
    ]
