# Generated by Django 5.2.7 on 2025-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0006_alter_cycletime_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='privacy',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('no_one_except', 'никому, кроме'), ('nobody', 'никому')], default='nobody', max_length=20),
        ),
    ]
