# Generated by Django 5.2.7 on 2025-12-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0007_alter_task_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_criterias', to='my_workflows.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
