# Generated by Django 5.2.7 on 2025-12-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0008_acceptancecriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
