# Generated by Django 5.2.7 on 2025-12-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0010_alter_task_options_timeentry'),
        ('profiles', '0011_alter_profileskill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, default='Общее', max_length=100, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_workflows.project'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='profiles.profile')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='my_workflows.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['profile', 'project'], name='my_workflow_profile_96546a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('profile', 'project')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['profile', 'tag'], name='my_workflow_profile_ad88ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('profile', 'tag')},
        ),
    ]
