# Generated by Django 5.2.7 on 2025-12-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0011_project_task_project_tag_and_more'),
        ('profiles', '0011_alter_profileskill_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='my_workflow_profile_96546a_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_tags', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tags', to='my_workflows.task'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('profile', 'name')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['profile', 'name'], name='my_workflow_profile_ab1426_idx'),
        ),
    ]
