# Generated by Django 5.2.7 on 2025-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0012_remove_project_my_workflow_profile_96546a_idx_and_more'),
        ('profiles', '0011_alter_profileskill_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='my_workflow_profile_ad88ef_idx',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('profile', 'name')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['profile', 'name'], name='my_workflow_profile_d594ba_idx'),
        ),
    ]
