# Generated by Django 5.2.7 on 2025-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0013_remove_tag_my_workflow_profile_ad88ef_idx_and_more'),
        ('profiles', '0011_alter_profileskill_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='my_workflow_profile_d594ba_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('profile', 'name', 'task')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['profile', 'name', 'task'], name='my_workflow_profile_10af2e_idx'),
        ),
    ]
