# Generated by Django 5.2.7 on 2025-12-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_workflows', '0014_remove_tag_my_workflow_profile_d594ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='my_workflows.project'),
        ),
    ]
