# Generated by Django 5.2.7 on 2025-12-10 11:11

import apps.resume.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_profile_city_profile_country_profile_edu_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Кластер навыков',
                'verbose_name_plural': 'Кластеры навыков',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное название сертификата')),
                ('link_to_sertificate', models.URLField(blank=True, null=True, verbose_name='Ссылка на сертификат')),
                ('image', models.ImageField(blank=True, default='', upload_to=apps.resume.models.user_sertificate_path)),
                ('file', models.FileField(blank=True, default='', upload_to=apps.resume.models.user_sertificate_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(blank=True, null=True, verbose_name='Профессиональное резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания работодатель')),
                ('indastry_desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание ниши работодателя')),
                ('start_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год начала сотрудничества')),
                ('end_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год окончания сотрудничества')),
                ('start_position', models.CharField(blank=True, null=True, verbose_name='Стартовая должность')),
                ('final_position', models.CharField(blank=True, null=True, verbose_name='Финальная должность')),
                ('is_current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Место работы или сотрудничества',
                'verbose_name_plural': 'Места работы или сотрудничества',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='WorkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=500, null=True, verbose_name='[Действие] [Результат с цифрой] для [Контекст/Масштаб], используя [Метод/Инструмент], чтобы [Решаемая проблема]')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='resume.workexperience')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('A1', 'Начальный (A1)'), ('A2', 'Элементарный (A2)'), ('B1', 'Средний (B1)'), ('B2', 'Выше среднего (B2)'), ('C1', 'Продвинутый (C1)'), ('C2', 'В совершенстве (C2)'), ('N', 'Родной')], max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'unique_together': {('profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillcluster')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'unique_together': {('name', 'profile')},
            },
        ),
    ]
