# Generated by Django 5.2.7 on 2025-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
