# Generated by Django 5.2.7 on 2025-12-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_city_profile_country_profile_edu_level_and_more'),
        ('resume', '0002_alter_language_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcluster',
            options={'ordering': ['order', 'cluster_name'], 'verbose_name': 'Кластер навыков', 'verbose_name_plural': 'Кластеры навыков'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='skillcluster',
            old_name='name',
            new_name='cluster_name',
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('skill_name', 'profile')},
        ),
    ]
