# Generated by Django 5.2.7 on 2025-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_language_privacy_sertificate_privacy_skill_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости владения языком'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости сертификата'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости конкретного навыка'),
        ),
        migrations.AlterField(
            model_name='skillcluster',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости кластера навыков'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости всего резюме целиком'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости информации о работодателе'),
        ),
        migrations.AlterField(
            model_name='workresult',
            name='privacy',
            field=models.CharField(blank=True, choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10, verbose_name='Настройка видимости рабочего результата'),
        ),
    ]
