# Generated by Django 5.2.7 on 2025-12-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_language_privacy_alter_sertificate_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcluster',
            name='privacy',
        ),
    ]
