# Generated by Django 5.2.7 on 2025-12-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_skillcluster_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillcluster'),
        ),
    ]
