# Generated by Django 5.2.7 on 2025-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('arabic', 'Арабский'), ('amharic', 'Амхарский'), ('english', 'Английский'), ('afrikaans', 'Африкаанс'), ('albanian', 'Албанский'), ('armenian', 'Армянский'), ('azerbaijani', 'Азербайджанский'), ('bengali', 'Бенгальский'), ('belarusian', 'Белорусский'), ('burmese', 'Бирманский'), ('bulgarian', 'Болгарский'), ('bosnian', 'Боснийский'), ('catalan', 'Каталанский'), ('czech', 'Чешский'), ('chinese', 'Китайский'), ('danish', 'Датский'), ('dari', 'Дари'), ('dutch', 'Нидерландский'), ('dzongkha', 'Дзонг-кэ'), ('estonian', 'Эстонский'), ('filipino', 'Филиппинский'), ('finnish', 'Финский'), ('french', 'Французский'), ('georgian', 'Грузинский'), ('german', 'Немецкий'), ('greek', 'Греческий'), ('hebrew', 'Иврит'), ('hindi', 'Хинди'), ('croatian', 'Хорватский'), ('hungarian', 'Венгерский'), ('icelandic', 'Исландский'), ('indonesian', 'Индонезийский'), ('irish', 'Ирландский'), ('italian', 'Итальянский'), ('japanese', 'Японский'), ('kazakh', 'Казахский'), ('khmer', 'Кхмерский'), ('kinyarwanda', 'Киньяруанда'), ('kirundi', 'Кирунди'), ('korean', 'Корейский'), ('kyrgyz', 'Киргизский'), ('lao', 'Лаосский'), ('latvian', 'Латышский'), ('lithuanian', 'Литовский'), ('luxembourgish', 'Люксембургский'), ('macedonian', 'Македонский'), ('malagasy', 'Малагасийский'), ('malay', 'Малайский'), ('maltese', 'Мальтийский'), ('maori', 'Маори'), ('moldovan', 'Молдавский'), ('mongolian', 'Монгольский'), ('montenegrin', 'Черногорский'), ('nepali', 'Непальский'), ('norwegian', 'Норвежский'), ('pashto', 'Пушту'), ('persian', 'Персидский'), ('polish', 'Польский'), ('portuguese', 'Португальский'), ('romanian', 'Румынский'), ('russian', 'Русский'), ('samoan', 'Самоанский'), ('serbian', 'Сербский'), ('sinhala', 'Сингальский'), ('slovak', 'Словацкий'), ('slovene', 'Словенский'), ('somali', 'Сомалийский'), ('spanish', 'Испанский'), ('swahili', 'Суахили'), ('swedish', 'Шведский'), ('tajik', 'Таджикский'), ('tamil', 'Тамильский'), ('thai', 'Тайский'), ('turkish', 'Турецкий'), ('turkmen', 'Туркменский'), ('ukrainian', 'Украинский'), ('urdu', 'Урду'), ('uzbek', 'Узбекский'), ('vietnamese', 'Вьетнамский'), ('welsh', 'Валлийский'), ('berber', 'Берберский'), ('quechua', 'Кечуа'), ('aymara', 'Аймара'), ('guarani', 'Гуарани'), ('dhivehi', 'Мальдивский'), ('tigrinya', 'Тигринья'), ('sesotho', 'Сесото'), ('setswana', 'Сетсвана'), ('chichewa', 'Чева'), ('kurdish', 'Курдский'), ('sango', 'Санго'), ('tok pisin', 'Ток-писин'), ('hiri motu', 'Хири-моту'), ('nauruan', 'Науруанский'), ('palauan', 'Палауский'), ('marshallese', 'Маршалльский'), ('kiribati', 'Гилбертский'), ('tongan', 'Тонганский'), ('fijian', 'Фиджийский'), ('bislama', 'Бислама'), ('haitian creole', 'Гаитянский креольский'), ('tetum', 'Тетум'), ('tswana', 'Тсвана'), ('swati', 'Свати')], max_length=50, null=True),
        ),
    ]
