# Generated by Django 5.2.7 on 2025-12-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePrivacySettings',
            fields=[
                ('first_name', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('last_name', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('profession', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('short_desc', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('full_desc', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('wallpaper', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('avatar', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('link_to_instagram', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('link_to_telegram', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('link_to_github', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('link_to_vk', models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='profiles.profile')),
                ('blacklist', models.ManyToManyField(blank=True, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к профилю пользователя',
                'verbose_name_plural': 'Доступ к профилям пользователей',
            },
        ),
    ]
