# Generated by Django 5.2.7 on 2025-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprivacysettings',
            name='city',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='country',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='edu_level',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='graduation_year',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='institution_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='middle_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='relocation',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='work_format',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
    ]
