# Generated by Django 5.2.7 on 2025-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_settings', '0002_profileprivacysettings_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprivacysettings',
            name='edu_levels',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='profileprivacysettings',
            name='work_formats',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
    ]
