# Generated by Django 5.2.7 on 2025-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_settings', '0005_remove_profileprivacysettings_edu_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprivacysettings',
            name='edu_levels',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('nobody', 'никому')], default='all', max_length=10),
        ),
    ]
