# Generated by Django 5.2.7 on 2025-12-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_settings', '0006_profileprivacysettings_edu_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileprivacysettings',
            name='edu_levels',
        ),
    ]
