# Generated by Django 5.2.7 on 2025-12-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_settings', '0007_remove_profileprivacysettings_edu_levels'),
        ('profiles', '0011_alter_profileskill_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprivacysettings',
            name='whitelist',
            field=models.ManyToManyField(blank=True, related_name='profile_whitelist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='avatar',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='profile_blacklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='city',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='country',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='edu_level',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='first_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='full_desc',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='graduation_year',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='institution_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='last_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_github',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_instagram',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_telegram',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_vk',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='middle_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='profession',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_privacies', serialize=False, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='relocation',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='short_desc',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='wallpaper',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='work_formats',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'всем, кроме...'), ('not_nobody', 'никому, кроме'), ('nobody', 'никому')], default='all', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskPrivacySettings',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_privacies', serialize=False, to='profiles.profile')),
                ('blacklist', models.ManyToManyField(blank=True, related_name='task_blacklist', to=settings.AUTH_USER_MODEL)),
                ('whitelist', models.ManyToManyField(blank=True, related_name='task_whitelist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к задаче пользователя',
                'verbose_name_plural': 'Доступ к задачам пользователей',
            },
        ),
    ]
