# Generated by Django 5.2.7 on 2025-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
