# Generated by Django 5.2.7 on 2025-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_blocked_postcomment_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
